### ISSUE TITLE
Data size

### ISSUE THREAD

**Issue by nsankar** [juangamella/ges#2]
@juangamella Thanks for developing this interesting package. Any idea or your observations about the typical size of the observational data that is required to learn the optimal structures?  

Thanks in advance.

**Comment by juangamella** [comment]
Hi @nsankar,

Thanks for your question! That depends greatly on the particular data-generating structure and the number of variables. You can get an idea from Figure 7 in the original GES paper: https://www.jmlr.org/papers/volume3/chickering02b/chickering02b.pdf

Note: Please avoid opening an issue the next time as their purpose is to report bugs in the software. You are more than welcome to write me an email instead (you can my address in the readme).

Best,
Juan
